name: CI/CD Main Pipeline

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      service_type:
        required: false
        type: string
      build_folder:
        required: false
        type: string
      active_branch:
        required: false
        type: string
      build_version:
        required: false
        type: string
      repository_name:
        required: true
        type: string
      release_version:
        required: false
        type: string
      commit_message:
        required: false
        type: string      
      image_name:
        required: true
        type: string
      image:
        required: false
        type: string
        default: ubuntu-latest
        
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      AUTH_TOKEN:
        required: true
      TELEGRAM_NOTIFICATION_TOKEN:
        required: false
      TELEGRAM_GITHAB_CHAT_ID:
        required: false
      SSH_KEY_FOR_DEPLOY:
        required: true
      SSH_ACCESS_ALPHA_01:
        required: true
      SSH_ACCESS_BETA_01:
        required: true
      SSH_ACCESS_DEMO_01:
        required: true
        
jobs:         
#-------------- TEST RUST ----------------#
  test-rust:
    if: ${{ inputs.language == 'rust' && github.event_name != 'release' && github.event.action != 'published' && inputs.build_version == '' }}
    runs-on: ${{ inputs.image }}
    name: "[RUST] Test code"
    outputs:
      rust-status: ${{ job.status }}

    steps:
      - uses: actions/checkout@v4

      # - name: Check dump all context
      #   uses: crazy-max/ghaction-dump-context@v2
      
      - name: Get last commit message
        id: get_commit
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "-------- COMMIT_MESSAGE: $COMMIT_MESSAGE"

      - name: Cache cargo build
        if: ${{ inputs.active_branch != 'main' && inputs.active_branch != 'beta' }}
        uses: actions/cache@v3
        with:
          path: |
            target
            .cargo
          key: ${{ runner.os }}-cargo-test-${{ inputs.repository_name }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-${{ inputs.repository_name }}-
            ${{ runner.os }}-cargo-test-

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - run: openssl version  

      - name: Start cargo test
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: test

#-------------- TEST C# ----------------#
  test-csharp:
    if: ${{ inputs.language == 'csharp' && github.event_name != 'release' && github.event.action != 'published' && inputs.build_version == '' }}
    runs-on: ${{ inputs.image }}
    name: "[C#] Test code"
    outputs:
      csharp-status: ${{ job.status }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.*
          source-url: https://nuget.pkg.github.com/my-prop-trading/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Start csharp test
        run: |
          dotnet build
          dotnet test

#-------------- Send ERROR test notification ----------------#
  notify-telegram-test-error:
    needs: [test-rust, test-csharp]
    runs-on: ${{ inputs.image }}
    name: "Send ERROR test notification"
    if: failure()
    steps:
      - name: Send test error notification
        run: |
          user="Triggered by: ${{ github.actor }}"
          reason="Last commit: ${{ github.event.head_commit.message }}"
          date="Date: $(date -d "+2 hours" +"%d.%m.%Y %H:%M:%S")"
          pipeline_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        
          # send Telegram notification:
          curl --request POST --header "Content-Type: application/json" \
            --data "{\"text\":\"[${{ inputs.language }}] Test error:\n\n>>>  ${{ inputs.repository_name }}\n\n $user\n $reason\n $date\n\n Please check action here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}" \
            "https://api.telegram.org/bot${{ secrets.TELEGRAM_NOTIFICATION_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_GITHAB_CHAT_ID }}"

#-------------- BUILD RUST ----------------#
  build-rust:
    if: ${{ (inputs.language == 'rust' && github.event_name == 'release' && github.event.action == 'published') || (inputs.language == 'rust' && inputs.build_version != '') }}
    runs-on: ${{ inputs.image }}
    name: "[RUST] Build code"
    outputs:
      success: ${{ steps.set-success.outputs.success }}
      rust-build-status: ${{ job.status }}
    steps:
      - uses: actions/checkout@v4

      # - name: Check dump all context
      #   uses: crazy-max/ghaction-dump-context@v2

      - name: Get release version
        id: get_version
        run: |
          if [ -z "${{ inputs.build_version }}" ]; then
            VERSION="${{ inputs.release_version }}"
          else
            VERSION="${{ inputs.build_version }}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Using version: $VERSION"

      # - name: Get last commit message
      #   id: get_commit
      #   run: |
      #     COMMIT_MESSAGE=$(git log -1 --pretty=%B)
      #     echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
      #     echo "Last commit: $COMMIT_MESSAGE"
        
      - name: Cache cargo build
        if: ${{ inputs.active_branch != 'main' && inputs.active_branch != 'beta' }}
        uses: actions/cache@v3
        with:
          path: |
            target
            .cargo
          key: ${{ runner.os }}-cargo-build-${{ inputs.repository_name }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-${{ inputs.repository_name }}-
            ${{ runner.os }}-cargo-build-

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Update version in Cargo.toml
        run: sed -i -e 's/^version = .*/version = "${{ env.VERSION }}"/' Cargo.toml

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - run: openssl version

      # Install dependencies
      - run: sudo apt update
        continue-on-error: true
      - run: sudo apt install -y build-essential libglib2.0-dev pkg-config libssl-dev libgtk-3-dev
      - run: sudo apt update && sudo apt upgrade -y
        continue-on-error: true
      - run: sudo apt-get install javascriptcoregtk-4.1 libsoup-3.0 webkit2gtk-4.1 -y

      - name: Build project
        run: cargo build --release

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: .
          registry: docker.io
          repository: ${{ inputs.image_name }}
          tags: ${{ env.VERSION }}

      - name: Set success output
        id: set-success
        run: echo "::set-output name=success::true"
          
  #-------------- BUILD C# ----------------#
  build-csharp:
    if: ${{ (inputs.language == 'csharp' && github.event_name == 'release' && github.event.action == 'published') || (inputs.language == 'csharp' && inputs.build_version != '') }}
    runs-on: ${{ inputs.image }}
    name: "[C#] Build code"
    outputs:
      success: ${{ steps.set-success.outputs.success }}
      csharp-build-status: ${{ job.status }}
    steps:
      - uses: actions/checkout@v4

      # - name: Get release version
      #   id: get_version
      #   run: |
      #     echo "VERSION=${{ inputs.release_version }}" >> $GITHUB_ENV
      #     echo "VERSION-RC=$(echo ${{ inputs.release_version }} | sed 's/-.*//')"  >> $GITHUB_ENV

      - name: Get release version
        id: get_version
        run: |
          if [ -z "${{ inputs.build_version }}" ]; then
            VERSION="${{ inputs.release_version }}"
          else
            VERSION="${{ inputs.build_version }}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          VERSION_RC=$(echo $VERSION | sed 's/-.*//')
          echo "VERSION-RC=$VERSION_RC" >> $GITHUB_ENV
          echo "Using version: $VERSION"
          echo "Using version for AssemblyVersion: $VERSION_RC"
          
      - name: Change version in config file
        run: |
          cd ${{ inputs.build_folder }}
          ver=${{ env.VERSION-RC }}
          sed -i "s|<Version>.*|<Version>${ver}<\/Version>|g" ${{ inputs.build_folder }}.csproj
          cat ${{ inputs.build_folder }}.csproj
          
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.*
          source-url: https://nuget.pkg.github.com/my-prop-trading/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  
      - name: Restore microservice
        run: dotnet restore
        continue-on-error: true
  
      - name: Build microservice
        run: dotnet build --no-restore --configuration Release /p:AssemblyVersion=${{ env.VERSION-RC }}
  
      - name: Publish microservice
        run: dotnet publish ./${{ inputs.build_folder }}/${{ inputs.build_folder }}.csproj --configuration Release /p:AssemblyVersion=${{ env.VERSION-RC }} --output ./publish-api
  
      - name: Check Service dir
        run: ls -la ./publish-api
          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: ./publish-api
          registry: docker.io
          repository: ${{ inputs.image_name }}
          tags: ${{ env.VERSION }}

      - name: Set success output
        id: set-success
        run: echo "::set-output name=success::true"

  #-------------- DEPLOY TO SERVER ----------------#
  deploy-on-server:
    # if: ${{ (success() && github.event_name == 'release' && github.event.action == 'published') || (success() && inputs.build_version != '') }}
    needs: [ build-csharp, build-rust ]
    if: |
      always()
      && contains(needs.*.result, 'success')
      && !contains(needs.*.result, 'failure')
    # needs: [ build-csharp]
    # if: job.build-csharp.outputs.success == 'true' || job.build-rust.outputs.success == 'true'
    # if: ${{ (success() && github.job == build-csharp) || (success() && github.job == build-rust) }}
    # if: ${{ (github.event_name == 'release' && github.event.action == 'published') || (inputs.build_version != '') }}
    # needs: [ build-csharp, build-rust ]
    # if: needs.build-csharp.outputs.success == 'true' || needs.build-rust.outputs.success == 'true'
    runs-on: ${{ inputs.image }}
    name: "Deploy on server"
    # if: success()
    steps:
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_FOR_DEPLOY }}
          
      # - name: Check dump all context
      #   uses: crazy-max/ghaction-dump-context@v2

      - name: Get release version
        id: get_version
        run: |
          if [ -z "${{ inputs.build_version }}" ]; then
            VERSION="${{ inputs.release_version }}"
          else
            VERSION="${{ inputs.build_version }}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Using version: $VERSION"

      - name: Deploy to ALPHA
        if: ${{ inputs.active_branch != 'main' && inputs.active_branch != 'beta' }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_ACCESS_ALPHA_01 }} << 'EOF'
            echo "------ Starting deployment... ------"
            cd ~/docker-infrastructure/microservices/${{ inputs.repository_name }}
            pwd
            ls -la
            git pull
            # reg=s"|/${{ inputs.repository_name }}:[0-9].*|/${{ inputs.repository_name }}:${{ inputs.build_version }}|g"
            reg=s"|/${{ inputs.repository_name }}:[0-9].*|/${{ inputs.repository_name }}:${{ env.VERSION }}|g"
            echo $reg
            cat docker-compose.yaml
            echo "---------------------------------------"
            find . -type f -name "*.*ml" -exec sed -i -r $reg {} \;
            cat docker-compose.yaml
            docker-compose up -d
            #sleep 10
            git status
            if git status | grep -q modified; then
              # git commit -a -m "Update ${{ inputs.repository_name }}:${{ inputs.build_version }}"
              git commit -a -m "Update ${{ inputs.repository_name }}:${{ env.VERSION }}"
              git push
            fi
          EOF

      # - name: Send Telegram Notification
      #   env:
      #     TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_NOTIFICATION_TOKEN }}
      #     TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_GITHAB_CHAT_ID }}
      #   run: |
      #     curl -X POST \
      #     https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
      #     -d chat_id=$TELEGRAM_CHAT_ID \
      #     -d text="Deployment successful for ${{ inputs.repository_name }}:${{ inputs.build_version }}"


  
