name: CI/CD Main Pipeline

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      repository_name:
        required: true
        type: string

    secrets:
      TELEGRAM_NOTIFICATION_TOKEN:
        required: false
      TELEGRAM_GITHAB_CHAT_ID:
        required: false

#-------------- TEST RUST ----------------#
jobs:
  test-rust:
    if: ${{ inputs.language == 'rust' }}
    runs-on: ubuntu-latest
    name: Test code
    outputs:
      rust-status: ${{ job.status }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - run: openssl version  

      - name: Start cargo test
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: test

#-------------- TEST C# ----------------#
  test-csharp:
    if: ${{ inputs.language == 'csharp' }}
    runs-on: ubuntu-latest
    name: Test code
    outputs:
      csharp-status: ${{ job.status }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.*'

      - name: Start csharp test
        run: |
          dotnet build
          dotnet test

#-------------- Send ERROR test notification ----------------#
  notify-telegram-test-error:
    needs: [test-rust, test-csharp]
    runs-on: ubuntu-latest
    name: Send ERROR test notification 
    if: failure()
    steps:
      - name: Send test error notification
        run: |
          user="Triggered by: ${{ github.actor }}"
          reason="Last commit: ${{ github.event.head_commit.message }}"
          date="Date: $(date -d "+2 hours" +"%d.%m.%Y %H:%M:%S")"
          pipeline_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        
          # send Telegram notification:
          curl --request POST --header "Content-Type: application/json" \
            --data "{\"text\":\"[${{ inputs.language }}] Test error:\n\n>>>  ${{ inputs.repository_name }}\n\n $user\n $reason\n $date\n\n Please check action here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}" \
            "https://api.telegram.org/bot${{ secrets.TELEGRAM_NOTIFICATION_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_GITHAB_CHAT_ID }}"

