name: CI/CD Main Pipeline

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      repository_name:
        required: true
        type: string

    secrets:
      TELEGRAM_NOTIFICATION_TOKEN:
        required: false
      TELEGRAM_GITHAB_CHAT_ID:
        required: false

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # for TypeScript
      - name: Setup Node.js (for TypeScript)
        if: ${{ inputs.language == 'typescript' }}
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Testing (for TypeScript)
        if: ${{ inputs.language == 'typescript' }}
        run: |
          npm install
          npm test

      # for Rust
      - name: Setup RUST (for Rust)
        if: ${{ inputs.language == 'rust' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Testing (for Rust)
        if: ${{ inputs.language == 'rust' }}
        run: |
          cargo build --release
          cargo test --release

      # for C#
      - name: Setup .NET (for C#)
        if: ${{ inputs.language == 'csharp' }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.*'

      - name: Testing (for C#)
        if: ${{ inputs.language == 'csharp' }}
        run: |
          dotnet build
          dotnet test

  notify-telegram-test-error:
    needs: test
    runs-on: ubuntu-20.04
    if: failure()
    steps:
      - name: Send test error notification
        # env:
        #   TELEGRAM_NOTIFICATION_TOKEN: ${{ secrets.TELEGRAM_NOTIFICATION_TOKEN }}
        #   TELEGRAM_GITHAB_CHAT_ID: ${{ secrets.TELEGRAM_GITHAB_CHAT_ID }}
        run: |
          language="${{ inputs.language }}"
          project_name="${{ inputs.repository_name }}"
          user="Triggered by: ${{ github.actor }}"
          reason="Last commit: ${{ github.event.head_commit.message }}"
          date="Date: $(date -d "+2 hours" +"%d.%m.%Y %H:%M:%S")"
          pipeline_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          TELEGRAM_NOTIFICATION_TOKEN="${{ secrets.TELEGRAM_NOTIFICATION_TOKEN }}"
          TELEGRAM_GITHAB_CHAT_ID="${{ secrets.TELEGRAM_GITHAB_CHAT_ID }}"

          echo $language
          echo $project_name
          echo $user
          echo $reason
          echo $date
          echo $pipeline_url
          echo $TELEGRAM_NOTIFICATION_TOKEN
          echo $TELEGRAM_GITHAB_CHAT_ID
        
          # send Telegram notification:
          curl --request POST --header "Content-Type: application/json" \
            --data "{\"text\":\"[$language] Test error:\n\n>>> Project: $project_name\n$user\n$reason\n$date\n\nPlease check the pipeline here: $pipeline_url\"}" \
            "https://api.telegram.org/bot$TELEGRAM_NOTIFICATION_TOKEN/sendMessage?chat_id=$TELEGRAM_GITHAB_CHAT_ID"

