name: Cargo build

on:
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
      release_version:
        required: true
        type: string
      image_name:
        required: true
        type: string
      release_name:
        required: false
        type: string
        default: None
      release_body:
        required: false
        type: string
        default: None

    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      AUTH_TOKEN:
        required: true
      TELEGRAM_TO:
        required: false
      TELEGRAM_TOKEN:
        required: false


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Get the version
        # id: get_version
        # run: echo ::set-output name=VERSION::${{ inputs.release_version }}
        id: get_version
        run: echo "VERSION=${{ inputs.release_version }}" >> $GITHUB_OUTPUT
        
      - name: Updating version
        run: sed -i -e 's/^version = .*/version = "${{ steps.get_version.outputs.VERSION }}"/' Cargo.toml

      - name: Install Protoc
        uses: arduino/setup-protoc@v1       
      - run: openssl version

      - run: echo $LD_LIBRARY_PATH
    
      - run: sudo apt install build-essential -y
      - run: sudo apt install libglib2.0-dev -y
      - run: sudo apt install pkg-config libssl-dev -y
      - run: sudo apt install libgtk-3-dev -y

      - run: sudo apt update -y
      - run: sudo apt upgrade -y
    
      - run: sudo apt-get install javascriptcoregtk-4.1 libsoup-3.0 webkit2gtk-4.1 -y

      - run: cargo build --release

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: |          
          echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin   
      - name: Docker Build and Publish
        run: |          
          docker build -t ${{ inputs.image_name }}:${{ steps.get_version.outputs.VERSION }} .
          docker push ${{ inputs.image_name }}:${{ steps.get_version.outputs.VERSION }}
          
      - name: SUMMARY
        run: |
          echo "Docker image:" >> $GITHUB_STEP_SUMMARY
          echo "${{ inputs.image_name }}:${{ steps.get_version.outputs.VERSION }}" >> $GITHUB_STEP_SUMMARY
  
  docker-deploy:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
    - name: Get the version
      # id: get_version
      # run: echo ::set-output name=VERSION::${{ inputs.release_version }}
      id: get_version
      run: echo "VERSION=${{ inputs.release_version }}" >> $GITHUB_OUTPUT
        
    - name: get uat docker yamls
      uses: actions/checkout@v3
      with:
        repository: my-prop-trading/docker-infrastructure
        ref: main
        token: ${{ secrets.AUTH_TOKEN }}
    - run: |
        pwd
        ls -la
        reg=s"|/${{ inputs.repository_name }}:[0-9].*|/${{ inputs.repository_name }}:${{ steps.get_version.outputs.VERSION }}|g"
        echo $reg
        find . -type f -name "*.*ml" -exec sed -i -r $reg {} \;
        git config user.name github-actions
        git config user.email github-actions@github.com
        if git status | grep -q modified; then git commit -a -m "Update ${{ inputs.repository_name }}:${{ steps.get_version.outputs.VERSION }}" && git push; fi

  notify:
    name: notify release
    needs: [build, docker-deploy]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:

      - id: secrets
        run: |
          echo HAS_TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN != '' }} >> $GITHUB_OUTPUT

      - name: Get the version
        id: get_version
        run: echo "VERSION=${{ inputs.release_version }}" >> $GITHUB_OUTPUT
      # - name: Version
      #   shell: bash
      #   run: echo VERSION=${{ inputs.release_version }} >> $GITHUB_ENV

      - name: Timestamp
        shell: bash
        id: time_data
        run: |
          TIMESTAMP=${{ inputs.build_timestamp }}
          if [[ -z ${TIMESTAMP} ]]; then
            TIMESTAMP=$(date --utc +'%F %H:%M')
          fi
          echo TIMESTAMP=${TIMESTAMP} >> $GITHUB_OUTPUT
          
      - name: Telegram Notify
        if: steps.secrets.outputs.HAS_TELEGRAM_TOKEN == 'true'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>Released:</b> <i>${{ inputs.repository_name }}</i>. 
            <b>Version:</b> <i>${{ steps.get_version.outputs.VERSION }}</i>
            <b>Date:</b> <i>${{ steps.time_data.outputs.TIMESTAMP }} UTC</i>
            ---
            <b>Release Name:</b> <i>${{ github.event.release.name }}</i>
            <b>Release body:</b> <i>${{ github.event.release.body }}</i>
            <b>Jira Version:</b> <code>"${{ inputs.image_name }}:${{ steps.get_version.outputs.VERSION }}"</code>
            ---
            <b>ID:</b> <i>${{ github.run_id }}</i>
            <b>Actor:</b> <tg-spoiler>${{ github.actor }}</tg-spoiler>
            
