name: set secrets for repos
on:
  push:
# on:
#   workflow_dispatch:
#     inputs:
#       repository:
#         description: 'repository'
#         required: true
#         type: string

jobs:
  set_secrets:
    strategy:
      matrix:
        keys: [DOCKER_USERNAME, DOCKER_PASSWORD]
        include:
          - environment: uat
            DOCKER_USER: DOCKER_USER
            DOCKER_PASS: DOCKER_PASSWORD
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}]
    runs-on: ubuntu-20.04
    steps:
    - name: test keys
      run: echo ${{ matrix.keys }}
    - name: test values
      run: echo ${{ secrets[matrix.DOCKER_USER] }}
      
#     - name: set docker username
#       uses: hmanzur/actions-set-secret@v2.0.0
#       with:
#         name: 'DOCKER_USERNAME'
#         value: ${{ secrets.DOCKER_USERNAME }}
#         repository: my-prop-trading/${{ inputs.repository }}
#         token: ${{ secrets.AUTH_TOKEN }}

#     - name: set docker password
#       uses: hmanzur/actions-set-secret@v2.0.0
#       with:
#         name: 'DOCKER_PASSWORD'
#         value: ${{ secrets.DOCKER_PASSWORD }}
#         repository: my-prop-trading/${{ inputs.repository }}
#         token: ${{ secrets.AUTH_TOKEN }}
