name: set secrets for repos

on:
  workflow_dispatch:

jobs:
  set_secrets:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        repos:
          - auth-rest-api
          - trader-creds-flows-grpc
          - key-value-rest-api
          - web-terminal
          - rest-api-wl-shared
          - my-nosql-contracts
          - prop-engine-sb-contracts
          - personal-data-rest-api
          - personal-data-flows-grpc
          - proto-files
          - key-value-flows-grpc
          - Backoffice
          - emailsender
          - confirmation-email-sender
          - Service.BackofficeCreds
          - metatrader-rest-api
          - metatrader4-bridge
          - trading-package-flows-grpc
          - trading-package-rest-api
          - metatrader4-flows-grpc
          - trader-accounts-rest-api
          - dashboard-rest-api
          - trader-accounts-flows-grpc
          - metatrader5-flows-grpc
          - orders-flows-grpc
          - orders-rest-api
          - account-balances-flows-grpc
          - account-chart-flows-grpc
          - account-history-flows-grpc
          - account-history-rest-api
          - client-audit-log-flows-grpc
          - trading-scenarios-flows-grpc
          - sumsub-connector
          - kyc-flows-grpc
          - kyc-rest-api
          - payout-flows-grpc
          - sumsub-bridge-flows-grpc
          - sumsub-webhook
          - payouts-rest-api
          - metatrader-eod-flows-grpc
          - comments-flows-grpc
    steps:
    - name: set docker username to repo  ${{ matrix.repos }}
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'DOCKER_USERNAME'
        value: ${{ secrets.DOCKER_USERNAME }}
        repository: my-prop-trading/${{ matrix.repos }}
        token: ${{ secrets.AUTH_TOKEN }}

    - name: set docker password to repo ${{ matrix.repos }}
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'DOCKER_PASSWORD'
        value: ${{ secrets.DOCKER_PASSWORD }}
        repository: my-prop-trading/${{ matrix.repos }}
        token: ${{ secrets.AUTH_TOKEN }}
        
    - name: set docker password to repo ${{ matrix.repos }}
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'AUTH_TOKEN'
        value: ${{ secrets.AUTH_TOKEN }}
        repository: my-prop-trading/${{ matrix.repos }}
        token: ${{ secrets.AUTH_TOKEN }}

    - name: set telegram id to repo ${{ matrix.repos }}
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'TELEGRAM_TO'
        value: ${{ secrets.TELEGRAM_TO }}
        repository: my-prop-trading/${{ matrix.repos }}
        token: ${{ secrets.AUTH_TOKEN }}

    - name: set telegram token to repo ${{ matrix.repos }}
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'TELEGRAM_TOKEN'
        value: ${{ secrets.TELEGRAM_TOKEN }}
        repository: my-prop-trading/${{ matrix.repos }}
        token: ${{ secrets.AUTH_TOKEN }}
