name: set secrets for repos

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'repository'
        required: true
        type: string

jobs:
  set_secrets:
    runs-on: ubuntu-20.04
    steps:
    - name: set docker username to repo ${{ inputs.repository }}
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'DOCKER_USERNAME'
        value: ${{ secrets.DOCKER_USERNAME }}
        repository: my-prop-trading/${{ inputs.repository }}
        token: ${{ secrets.AUTH_TOKEN }}
        # token: ${{ secrets.GITHUB_TOKEN }}

    - name: set docker password to repo ${{ inputs.repository }}
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'DOCKER_PASSWORD'
        value: ${{ secrets.DOCKER_PASSWORD }}
        repository: my-prop-trading/${{ inputs.repository }}
        token: ${{ secrets.AUTH_TOKEN }}
        
    - name: set docker password to repo ${{ inputs.repository }}
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'AUTH_TOKEN'
        value: ${{ secrets.AUTH_TOKEN }}
        repository: my-prop-trading/${{ inputs.repository }}
        token: ${{ secrets.AUTH_TOKEN }}

    - name: set telegram id to repo ${{ inputs.repository }}
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'TELEGRAM_TO'
        value: ${{ secrets.TELEGRAM_TO }}
        repository: my-prop-trading/${{ inputs.repository }}
        token: ${{ secrets.AUTH_TOKEN }}

    - name: set telegram token to repo ${{ inputs.repository }}
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'TELEGRAM_TOKEN'
        value: ${{ secrets.TELEGRAM_TOKEN }}
        repository: my-prop-trading/${{ inputs.repository }}
        token: ${{ secrets.AUTH_TOKEN }}
