name: set secrets for repos
on:
  push:
# on:
#   workflow_dispatch:
#     inputs:
#       repository:
#         description: 'repository'
#         required: true
#         type: string

jobs:
  set_secrets:
    strategy:
      matrix:
        keys: [DOCKER-USERNAME, DOCKER-PASSWORD]
        values: ${{ secrets.DOCKER_USERNAME }}, ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-20.04
    steps:
    - name: test keys
      run: echo ${{ matrix.keys }}
    - name: test values
      run: echo ${{ matrix.values }}
      
#     - name: set docker username
#       uses: hmanzur/actions-set-secret@v2.0.0
#       with:
#         name: 'DOCKER_USERNAME'
#         value: ${{ secrets.DOCKER_USERNAME }}
#         repository: my-prop-trading/${{ inputs.repository }}
#         token: ${{ secrets.AUTH_TOKEN }}

#     - name: set docker password
#       uses: hmanzur/actions-set-secret@v2.0.0
#       with:
#         name: 'DOCKER_PASSWORD'
#         value: ${{ secrets.DOCKER_PASSWORD }}
#         repository: my-prop-trading/${{ inputs.repository }}
#         token: ${{ secrets.AUTH_TOKEN }}
