name: Test build

on:
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
      release_version:
        required: true
        type: string
      image_name:
        required: true
        type: string

    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      AUTH_TOKEN:
        required: true
      TELEGRAM_TO:
        required: false
      TELEGRAM_TOKEN:
        required: false


jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M')"

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${{ inputs.release_version }}
  
      - name: Timestamp
        shell: bash
        run: |
          TIMESTAMP=${{ inputs.build_timestamp }}
          if [[ -z ${TIMESTAMP} ]]; then
            TIMESTAMP=$(date --utc +'%F %H:%M')
          fi
          echo TIMESTAMP=${TIMESTAMP} >> $GITHUB_ENV

      - name: Echo
        run: |
          echo "image_name: ${{ inputs.image_name }}"
          echo "VERSION: ${{ steps.get_version.outputs.VERSION }}"
          echo "Released: ${{ inputs.repository_name }}"
          echo "Version: ${{ inputs.release_version }}"
          echo "Date: ${{ steps.date.outputs.date }} UTC"
          echo "Release Name: ${{ inputs.release_name }}"
          echo "Changelog: ${{ inputs.release_body }}"
          echo "ID: ${{ github.run_id }}"
          echo "Message: ${{ github.event.commits[0].message }}"
          echo "TIMESTAMP: ${TIMESTAMP}"
          echo "actor: ${{ github.actor }}"

  dump:
    runs-on: ubuntu-latest
    steps:
      -
        name: Dump context
        uses: crazy-max/ghaction-dump-context@v2

  notify:
    name: notify release
    needs: [build]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:

      - id: secrets
        run: |
          echo HAS_TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN != '' }} >> $GITHUB_OUTPUT

      - name: Version
        shell: bash
        run: echo VERSION=${{ inputs.release_version }} >> $GITHUB_ENV

      - name: Timestamp
        shell: bash
        run: |
          TIMESTAMP=${{ inputs.build_timestamp }}
          if [[ -z ${TIMESTAMP} ]]; then
            TIMESTAMP=$(date --utc +'%F %H:%M')
          fi
          echo TIMESTAMP=${TIMESTAMP} >> $GITHUB_ENV
          
      - name: Telegram Notify
        if: steps.secrets.outputs.HAS_TELEGRAM_TOKEN == 'true'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>Released:</b> <i>${{ inputs.repository_name }}</i>. 
            <b>Version:</b> <i>${{ env.VERSION }}</i>
            <b>Date:</b> <i>${{ env.TIMESTAMP }} UTC</i>
            ---
            <b>Release Name:</b> <i>${{ github.event.release.name }}</i>
            <b>Release body:</b>\n <s>${{ github.event.release.body }}</s>
            ---
            <b>ID:</b> <i>${{ github.run_id }}</i>
            <b>Actor:</b> <tg-spoiler>${{ github.actor }}</tg-spoiler>
            
