name: test

on:
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: actions
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'DOCKER_USERNAME'
        value: ${{ secrets.DOCKER_USERNAME }}
        repository: my-prop-trading/${{ inputs.repository_name }}
        token: ${{ secrets.AUTH_TOKEN }}
